# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version = 4.2.0
group = net.splatcraft
java_version = 21

# Common
minecraft_version = 1.21.1
mod_name = Splatcraft
mod_author = Cibernet, Octol1ttle
mod_id = splatcraft
license = MIT
credits = '''\
Thanks to Nintendo and Mojang, for making such great games!\
\
Programming and Design by Cibernet and Octol1ttle\
Models by Cibernet & JustHatless\
French translation by Flyse and Este\
Portuguese translation by gatoazulado\
Simplified Chinese translation by White Mind\
Spanish translation by Cibernet and Chichi\
Russian translation by jskces\
Italian translation by Alessio798\
\
Block of Power Eggs texture by rose bushes\
\
Special Thanks to Andante and seamuskills\
'''
description = '''\
Splatcraft is a Minecraft mod based on Nintendo's popular game Splatoon!\
This mod aims to add items and mechanics based on the game in a cohesive way, such as Turf Wars, Weapons, Squid Transformations and many more!\
'''

minecraft_version_range = [1.21.1, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version = 1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft = 1.21.1
parchment_version = 2024.11.17

# Fabric
fabric_version = 0.109.0+1.21.1
fabric_loader_version = 0.16.9

# Forge
forge_version = 52.0.28
forge_loader_version_range = [52,)

# NeoForge
neoforge_version = 21.1.116
neoforge_loader_version_range = [4,)

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.parallel = true

# Architectury
architectury_api_version = 13.0.8