plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
            jvmArguments = ["-XX:+AllowEnhancedClassRedefinition", "-XX:+IgnoreUnrecognizedVMOptions"]
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
            programArgument("--nogui")
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

javadoc {
    options.tags = ["apiNote"]
}

dependencies {
    implementation 'mysticdrew:common-networking-neoforge:1.0.16-1.21'
    implementation 'maven.modrinth:sodium:mc1.21.1-0.6.13-neoforge'
}

sourceSets.main.resources { srcDir 'src/generated/resources' }